[2] Call finish unexpected: 1 return true
